### ISSUE TITLE
I added player.postion.x += 5, but it doesn't work

### ISSUE THREAD

**Issue by merrymaker14** [pmndrs/react-xr#100]
Example: https://codesandbox.io/s/react-xr-paddle-demo-forked-7fh2r?file=/src/index.tsx:986-1014

**Comment by mwmwmw** [comment]
It's a spelling error

`player.postion.x += 5`

needs to be

`player.position.x += 5`

**Comment by merrymaker14** [comment]
Oh. Thank you very much!

**Comment by merrymaker14** [comment]
I'm sorry, bot player doesn't move anyway: https://codesandbox.io/s/react-xr-paddle-demo-forked-7fh2r?file=/src/index.tsx

**Comment by merrymaker14** [comment]
I tried at the beginning to write `useXREvent `outside `Stitch `function, but at that time I am not yet in VR mode and the `controllers `is `undefined`.

**Comment by mwmwmw** [comment]
Here is a fork. I could get the player moving on the x-axis when you squeeze, but it's a little hard to see because there is no frame of reference in the scene.

https://codesandbox.io/s/react-xr-paddle-demo-forked-4gw2q

There are many reasons why this wasn't working, but the main one is that `<Stitch />` was never added to the scene, so the event was never bound. 

Here is what I recommend. 

- Take all the components inside of `function App()` and move them outside the App function scope. 

In general, do not create new functional components within an existing function scope unless necessary. Pass in a prop, create a context provider, whatever. Doing things this way will make your code so much easier to use. These components will be re-initialized on every update you don't want to do.

```
✅ Do this.
function Box () {}
function Sphere() {}
function App() {
  return <VRCanvas>
      <Box />
      <Sphere />
  </VRCanvas>
}

⛔ Avoid this
function App() {
  
  function Box () {}
  function Sphere() {}
  
  return <VRCanvas>
      <Box />
      <Sphere />
  </VRCanvas>
}
```

- Make each component work before moving on to the next one. For example, you have a GLTF that is failing to load. I would fix that issue first. 

- When troubleshooting, focus on the part that isn't working by removing other components from your scene. It's easier to see problems occur this way.

- When using refs in useEffect or useFrame, check `ref.current` has a value before using it. 
- When using a ref with useEffect, specifically, add it to the dependency array. 

```
useEffect(()=>{
   if(myRef.current) {
    /* do something with myRef.current */
  }
}, [myRef])
```

- When not in VR mode, there are no controllers even if the controllers are plugged in. Similar to refs, check that controllers have a value before using. 

```
useFrame(()=>{
    if (controllers) 
    {
        /* do something */ 
    }
})
```

Good Luck!

**Comment by merrymaker14** [comment]
Thank you! I see now.
