### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `vr`.

### ISSUE THREAD

**Issue by Enijar** [pmndrs/react-xr#129]
With this set up (in development mode), I receive this warning in the console:

```console
Warning: Received `true` for a non-boolean attribute `vr`.
```

Code to reproduce:

```tsx
<VRCanvas flat linear dpr={1}>
  <mesh>
    <boxBufferGeometry />
    <meshBasicMaterial color="crimson" />
  </mesh>
</VRCanvas>
```

Is there a way to fix this warning?

**Comment by aaron-peloquin** [comment]
# Overview
I am getting the same issue, I have a workaround but not sure how it should be fixed. I have two possible fixes listed below

## Temporary Fix
This seems like it could be a temporary fix without causing other issues:
```
<VRCanvas vr="true">
```

The reason is that this [vr](https://github.com/pmndrs/react-xr/blob/2e89252ebea164732c80987bac0942e5604185e5/src/XR.tsx#L184) prop is being sent all the way down to the DOM element, and booleans cannot be set on DOM elements

## Possible Fixes
I'm not sure how this prop is used by the `<Canvas>` component on the line I linked above. The `<div>` it creates might actually need that attribute on it

### Stringify the prop and update TS
If it does, changing to a string here is ideal, but then we'd need a TS update, too

### Remove the attribute from DOM
Otherwise, if we don't need the `vr` attribute on the DOM element, then the parent library should remove `vr` from the `props` variable before it writes to its [div](https://github.com/pmndrs/react-three-fiber/blob/ba8e989c58e9a84f84003a0f684b13feea22bf29/packages/fiber/src/web/Canvas.tsx#L109-L112)

**Comment by CodyJasonBennett** [comment]
`vr` was deprecated in R3F v8. Try upgrading to `v4`(https://github.com/pmndrs/react-xr/releases/tag/v4.0.0) which removes such usage.
