### ISSUE TITLE
XR seems to be taking control over any camera

### ISSUE THREAD

**Issue by ablaszkiewicz** [pmndrs/react-xr#52]
I have created simple AR demo with portal - it works fine in web browser with AR disabled. Portal renders object placed in paralell scene and when I move arround it doesn't change position (as intended).

When I move to AR and launch this app on my phone strange things are happening. It seems like portal is rendering stuff based on my phone position. I have added a `THREE.CameraHelper` to see what is going on and it seems that XR takes control over my other-dimension camera and snaps its position and rotation to my device position and rotation.

I thought that maybe it just takes first camera created from code and sets is as an XR camera which is used to displaying thus I have created another `dummyCamera`. It turns out that no matter how many cameras I create (these cameras aren't even on current `THREE.Scene`), XR always takes control over them and snaps them to device transform

On PC with AR disabled I can see cameras' wireframes by using `THREE.CameraHelper` and on phone I can just see this helper stick to my position. How do I tell XR not to control cameras?

**Comment by MaartenBreeedveld** [comment]
I'm not shure if this is react-xr related or ThreeJS behaviour.
A suggestion perhaps: have you tried creating an actual react portal?

**Comment by CodyJasonBennett** [comment]
Can you provide a reproduction?

**Comment by jure** [comment]
I'm seeing the same thing. I think it's a Three.js issue. It gets updated due to https://github.com/mrdoob/three.js/blob/d0340e3a147e290fa86d14bc3ed97d8e1c20602e/src/renderers/WebGLRenderer.js#L983-L989

A workaround, if you have access to where the rendering is happening, is to flip the `cameraAutoUpdate` off before rendering:
```js
state.gl.xr.cameraAutoUpdate = false
state.gl.render(scene, state.camera)
state.gl.xr.cameraAutoUpdate = true
```    

I think Three.js should check if the camera that it wants to update is the `state.camera` and not just any camera. I'll think about it a bit more and submit a PR, if it checks out.

Here's a repro: https://codesandbox.io/s/react-xr-issue-52-repro-0m65f
